/* -*- Mode: JavaScript; coding: utf-8; tab-width: 3; indent-tabs-mode: tab; c-basic-offset: 3 -*-
 *******************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright create3000, Scheffelstraße 31a, Leipzig, Germany 2011.
 *
 * All rights reserved. Holger Seelig <holger.seelig@yahoo.de>.
 *
 * The copyright notice above does not evidence any actual of intended
 * publication of such source code, and is an unpublished work by create3000.
 * This material contains CONFIDENTIAL INFORMATION that is the property of
 * create3000.
 *
 * No permission is granted to copy, distribute, or create derivative works from
 * the contents of this software, in whole or in part, without the prior written
 * permission of create3000.
 *
 * NON-MILITARY USE ONLY
 *
 * All create3000 software are effectively free software with a non-military use
 * restriction. It is free. Well commented source is provided. You may reuse the
 * source in any way you please with the exception anything that uses it must be
 * marked to indicate is contains 'non-military use only' components.
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2015, 2016 Holger Seelig <holger.seelig@yahoo.de>.
 *
 * This file is part of the Cobweb Project.
 *
 * Cobweb is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 only, as published by the
 * Free Software Foundation.
 *
 * Cobweb is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License version 3 for more
 * details (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version 3
 * along with Cobweb.  If not, see <http://www.gnu.org/licenses/gpl.html> for a
 * copy of the GPLv3 License.
 *
 * For Silvio, Joy and Adi.
 *
 ******************************************************************************/


define ([
	"../Components/Networking/Anchor.js", // VRML
	"../Components/Shape/Appearance.js", // VRML
	"../Components/Geometry2D/Arc2D.js",
	"../Components/Geometry2D/ArcClose2D.js",
	"../Components/Sound/AudioClip.js",
	"../Components/EnvironmentalEffects/Background.js", // VRML
	//"../Components/RigidBodyPhysics/BallJoint.js",
	"../Components/Navigation/Billboard.js", // VRML
	"../Components/EventUtilities/BooleanFilter.js",
	"../Components/EventUtilities/BooleanSequencer.js",
	"../Components/EventUtilities/BooleanToggle.js",
	"../Components/EventUtilities/BooleanTrigger.js",
	"../Components/ParticleSystems/BoundedPhysicsModel.js",
	"../Components/Geometry3D/Box.js", // VRML
	"../Components/CADGeometry/CADAssembly.js",
	"../Components/CADGeometry/CADFace.js",
	"../Components/CADGeometry/CADLayer.js",
	"../Components/CADGeometry/CADPart.js",
	"../Components/Geometry2D/Circle2D.js",
	"../Components/Rendering/ClipPlane.js",
	//"../Components/RigidBodyPhysics/CollidableOffset.js",
	//"../Components/RigidBodyPhysics/CollidableShape.js",
	"../Components/Navigation/Collision.js", // VRML
	//"../Components/RigidBodyPhysics/CollisionCollection.js",
	//"../Components/RigidBodyPhysics/CollisionSensor.js",
	//"../Components/RigidBodyPhysics/CollisionSpace.js",
	"../Components/Rendering/Color.js", // VRML
	"../Components/Followers/ColorChaser.js",
	"../Components/Followers/ColorDamper.js",
	"../Components/Interpolation/ColorInterpolator.js", // VRML
	"../Components/Rendering/ColorRGBA.js",
	"../Components/CubeMapTexturing/ComposedCubeMapTexture.js",
	"../Components/Shaders/ComposedShader.js",
	//"../Components/Texturing3D/ComposedTexture3D.js",
	"../Components/Geometry3D/Cone.js", // VRML
	"../Components/ParticleSystems/ConeEmitter.js",
	//"../Components/RigidBodyPhysics/Contact.js",
	//"../Components/NURBS/Contour2D.js",
	//"../Components/NURBS/ContourPolyline2D.js",
	"../Components/Rendering/Coordinate.js", // VRML
	"../Components/Followers/CoordinateChaser.js",
	"../Components/Followers/CoordinateDamper.js",
	"../Components/NURBS/CoordinateDouble.js",
	"../Components/Interpolation/CoordinateInterpolator.js", // VRML
	"../Components/Interpolation/CoordinateInterpolator2D.js",
	"../Components/Geometry3D/Cylinder.js", // VRML
	"../Components/PointingDeviceSensor/CylinderSensor.js", // VRML
	//"../Components/DIS/DISEntityManager.js",
	//"../Components/DIS/DISEntityTypeMapping.js",
	"../Components/Lighting/DirectionalLight.js", // VRML
	"../Components/Geometry2D/Disk2D.js",
	//"../Components/RigidBodyPhysics/DoubleAxisHingeJoint.js",
	"../Components/Interpolation/EaseInEaseOut.js",
	"../Components/Geometry3D/ElevationGrid.js", // VRML
	//"../Components/DIS/EspduTransform.js",
	"../Components/ParticleSystems/ExplosionEmitter.js",
	"../Components/Geometry3D/Extrusion.js", // VRML
	//"../Components/Shape/FillProperties.js",
	"../Components/Shaders/FloatVertexAttribute.js",
	"../Components/EnvironmentalEffects/Fog.js", // VRML
	//"../Components/EnvironmentalEffects/FogCoordinate.js",
	"../Components/Text/FontStyle.js", // VRML
	"../Components/ParticleSystems/ForcePhysicsModel.js",
	"../Components/CubeMapTexturing/GeneratedCubeMapTexture.js",
	"../Components/Geospatial/GeoCoordinate.js",
	"../Components/Geospatial/GeoElevationGrid.js",
	"../Components/Geospatial/GeoLOD.js",
	"../Components/Geospatial/GeoLocation.js",
	"../Components/Geospatial/GeoMetadata.js",
	"../Components/Geospatial/GeoOrigin.js",
	"../Components/Geospatial/GeoPositionInterpolator.js",
	"../Components/Geospatial/GeoProximitySensor.js",
	"../Components/Geospatial/GeoTouchSensor.js",
	"../Components/Geospatial/GeoTransform.js",
	"../Components/Geospatial/GeoViewpoint.js",
	"../Components/Grouping/Group.js", // VRML
	//"../Components/H-Anim/HAnimDisplacer.js",
	//"../Components/H-Anim/HAnimHumanoid.js",
	//"../Components/H-Anim/HAnimJoint.js",
	//"../Components/H-Anim/HAnimSegment.js",
	//"../Components/H-Anim/HAnimSite.js",
	"../Components/CubeMapTexturing/ImageCubeMapTexture.js",
	"../Components/Texturing/ImageTexture.js", // VRML
	//"../Components/Texturing3D/ImageTexture3D.js",
	"../Components/Geometry3D/IndexedFaceSet.js", // VRML
	"../Components/Rendering/IndexedLineSet.js", // VRML
	"../Components/CADGeometry/IndexedQuadSet.js",
	"../Components/Rendering/IndexedTriangleFanSet.js",
	"../Components/Rendering/IndexedTriangleSet.js",
	"../Components/Rendering/IndexedTriangleStripSet.js",
	"../Components/Networking/Inline.js", // VRML
	"../Components/EventUtilities/IntegerSequencer.js",
	"../Components/EventUtilities/IntegerTrigger.js",
	"../Components/KeyDeviceSensor/KeySensor.js",
	"../Components/Navigation/LOD.js", // VRML
	"../Components/Layering/Layer.js",
	"../Components/Layering/LayerSet.js",
	"../Components/Layout/Layout.js",
	"../Components/Layout/LayoutGroup.js",
	"../Components/Layout/LayoutLayer.js",
	//"../Components/Picking/LinePickSensor.js",
	"../Components/Shape/LineProperties.js",
	"../Components/Rendering/LineSet.js",
	"../Components/Networking/LoadSensor.js",
	"../Components/EnvironmentalEffects/LocalFog.js",
	"../Components/Shape/Material.js", // VRML
	"../Components/Shaders/Matrix3VertexAttribute.js",
	"../Components/Shaders/Matrix4VertexAttribute.js",
	"../Components/Core/MetadataBoolean.js",
	"../Components/Core/MetadataDouble.js",
	"../Components/Core/MetadataFloat.js",
	"../Components/Core/MetadataInteger.js",
	"../Components/Core/MetadataSet.js",
	"../Components/Core/MetadataString.js",
	//"../Components/RigidBodyPhysics/MotorJoint.js",
	"../Components/Texturing/MovieTexture.js", // VRML
	//"../Components/Texturing/MultiTexture.js",
	//"../Components/Texturing/MultiTextureCoordinate.js",
	//"../Components/Texturing/MultiTextureTransform.js",
	"../Components/Navigation/NavigationInfo.js", // VRML
	"../Components/Rendering/Normal.js", // VRML
	"../Components/Interpolation/NormalInterpolator.js", // VRML
	//"../Components/NURBS/NurbsCurve.js",
	//"../Components/NURBS/NurbsCurve2D.js",
	//"../Components/NURBS/NurbsOrientationInterpolator.js",
	//"../Components/NURBS/NurbsPatchSurface.js",
	//"../Components/NURBS/NurbsPositionInterpolator.js",
	//"../Components/NURBS/NurbsSet.js",
	//"../Components/NURBS/NurbsSurfaceInterpolator.js",
	//"../Components/NURBS/NurbsSweptSurface.js",
	//"../Components/NURBS/NurbsSwungSurface.js",
	//"../Components/NURBS/NurbsTextureCoordinate.js",
	//"../Components/NURBS/NurbsTrimmedSurface.js",
	"../Components/Followers/OrientationChaser.js",
	"../Components/Followers/OrientationDamper.js",
	"../Components/Interpolation/OrientationInterpolator.js", // VRML
	"../Components/Navigation/OrthoViewpoint.js",
	//"../Components/Shaders/PackagedShader.js",
	"../Components/ParticleSystems/ParticleSystem.js",
	//"../Components/Picking/PickableGroup.js",
	"../Components/Texturing/PixelTexture.js", // VRML
	//"../Components/Texturing3D/PixelTexture3D.js",
	"../Components/PointingDeviceSensor/PlaneSensor.js", // VRML
	"../Components/ParticleSystems/PointEmitter.js",
	"../Components/Lighting/PointLight.js", // VRML
	//"../Components/Picking/PointPickSensor.js",
	"../Components/Rendering/PointSet.js", // VRML
	"../Components/Geometry2D/Polyline2D.js",
	"../Components/ParticleSystems/PolylineEmitter.js",
	"../Components/Geometry2D/Polypoint2D.js",
	"../Components/Followers/PositionChaser.js",
	"../Components/Followers/PositionChaser2D.js",
	"../Components/Followers/PositionDamper.js",
	"../Components/Followers/PositionDamper2D.js",
	"../Components/Interpolation/PositionInterpolator.js", // VRML
	"../Components/Interpolation/PositionInterpolator2D.js",
	//"../Components/Picking/PrimitivePickSensor.js",
	//"../Components/Shaders/ProgramShader.js",
	"../Components/EnvironmentalSensor/ProximitySensor.js", // VRML
	"../Components/CADGeometry/QuadSet.js",
	//"../Components/DIS/ReceiverPdu.js",
	"../Components/Geometry2D/Rectangle2D.js",
	//"../Components/RigidBodyPhysics/RigidBody.js",
	//"../Components/RigidBodyPhysics/RigidBodyCollection.js",
	"../Components/Followers/ScalarChaser.js",
	"../Components/Followers/ScalarDamper.js",
	"../Components/Interpolation/ScalarInterpolator.js", // VRML
	"../Components/Layout/ScreenFontStyle.js",
	"../Components/Layout/ScreenGroup.js",
	"../Components/Scripting/Script.js", // VRML
	"../Components/Shaders/ShaderPart.js",
	//"../Components/Shaders/ShaderProgram.js",
	"../Components/Shape/Shape.js", // VRML
	//"../Components/DIS/SignalPdu.js",
	//"../Components/RigidBodyPhysics/SingleAxisHingeJoint.js",
	//"../Components/RigidBodyPhysics/SliderJoint.js",
	"../Components/Sound/Sound.js", // VRML
	"../Components/Geometry3D/Sphere.js", // VRML
	"../Components/PointingDeviceSensor/SphereSensor.js", // VRML
	"../Components/Interpolation/SplinePositionInterpolator.js",
	"../Components/Interpolation/SplinePositionInterpolator2D.js",
	"../Components/Interpolation/SplineScalarInterpolator.js",
	"../Components/Lighting/SpotLight.js", // VRML
	"../Components/Interpolation/SquadOrientationInterpolator.js",
	"../Components/Grouping/StaticGroup.js",
	//"../Components/KeyDeviceSensor/StringSensor.js",
	"../Components/ParticleSystems/SurfaceEmitter.js",
	"../Components/Grouping/Switch.js", // VRML
	"../Components/Followers/TexCoordChaser2D.js",
	"../Components/Followers/TexCoordDamper2D.js",
	"../Components/Text/Text.js", // VRML
	"../Components/EnvironmentalEffects/TextureBackground.js",
	"../Components/Texturing/TextureCoordinate.js", // VRML
	"../Components/Texturing3D/TextureCoordinate3D.js",
	"../Components/Texturing3D/TextureCoordinate4D.js",
	//"../Components/Texturing/TextureCoordinateGenerator.js",
	"../Components/Texturing/TextureProperties.js",
	"../Components/Texturing/TextureTransform.js", // VRML
	"../Components/Texturing3D/TextureTransform3D.js",
	"../Components/Texturing3D/TextureTransformMatrix3D.js",
	"../Components/Time/TimeSensor.js", // VRML
	"../Components/EventUtilities/TimeTrigger.js",
	//"cobweb/Components/Titania/TouchGroup",
	"../Components/PointingDeviceSensor/TouchSensor.js", // VRML
	"../Components/Grouping/Transform.js", // VRML
	"../Components/EnvironmentalSensor/TransformSensor.js",
	//"../Components/DIS/TransmitterPdu.js",
	"../Components/Rendering/TriangleFanSet.js",
	"../Components/Rendering/TriangleSet.js",
	"../Components/Geometry2D/TriangleSet2D.js",
	"../Components/Rendering/TriangleStripSet.js",
	"../Components/Shape/TwoSidedMaterial.js",
	//"../Components/RigidBodyPhysics/UniversalJoint.js",
	"../Components/Navigation/Viewpoint.js", // VRML
	"../Components/Navigation/ViewpointGroup.js",
	"../Components/Layering/Viewport.js",
	"../Components/EnvironmentalSensor/VisibilitySensor.js", // VRML
	"../Components/ParticleSystems/VolumeEmitter.js",
	//"../Components/Picking/VolumePickSensor.js",
	"../Components/ParticleSystems/WindPhysicsModel.js",
	"../Components/Core/WorldInfo.js", // VRML
],
function (Anchor,
          Appearance,
          Arc2D,
          ArcClose2D,
          AudioClip,
          Background,
          //BallJoint,
          Billboard,
          BooleanFilter,
          BooleanSequencer,
          BooleanToggle,
          BooleanTrigger,
          BoundedPhysicsModel,
          Box,
          CADAssembly,
          CADFace,
          CADLayer,
          CADPart,
          Circle2D,
          ClipPlane,
          //CollidableOffset,
          //CollidableShape,
          Collision,
          //CollisionCollection,
          //CollisionSensor,
          //CollisionSpace,
          Color,
          ColorChaser,
          ColorDamper,
          ColorInterpolator,
          ColorRGBA,
          ComposedCubeMapTexture,
          ComposedShader,
          //ComposedTexture3D,
          Cone,
          ConeEmitter,
          //Contact,
          //Contour2D,
          //ContourPolyline2D,
          Coordinate,
          CoordinateChaser,
          CoordinateDamper,
          CoordinateDouble,
          CoordinateInterpolator,
          CoordinateInterpolator2D,
          Cylinder,
          CylinderSensor,
          //DISEntityManager,
          //DISEntityTypeMapping,
          DirectionalLight,
          Disk2D,
          //DoubleAxisHingeJoint,
          EaseInEaseOut,
          ElevationGrid,
          //EspduTransform,
          ExplosionEmitter,
          Extrusion,
          //FillProperties,
          FloatVertexAttribute,
          Fog,
          //FogCoordinate,
          FontStyle,
          ForcePhysicsModel,
          GeneratedCubeMapTexture,
          GeoCoordinate,
          GeoElevationGrid,
          GeoLOD,
          GeoLocation,
          GeoMetadata,
          GeoOrigin,
          GeoPositionInterpolator,
          GeoProximitySensor,
          GeoTouchSensor,
          GeoTransform,
          GeoViewpoint,
          Group,
          //HAnimDisplacer,
          //HAnimHumanoid,
          //HAnimJoint,
          //HAnimSegment,
          //HAnimSite,
          ImageCubeMapTexture,
          ImageTexture,
          //ImageTexture3D,
          IndexedFaceSet,
          IndexedLineSet,
          IndexedQuadSet,
          IndexedTriangleFanSet,
          IndexedTriangleSet,
          IndexedTriangleStripSet,
          Inline,
          IntegerSequencer,
          IntegerTrigger,
          KeySensor,
          LOD,
          Layer,
          LayerSet,
          Layout,
          LayoutGroup,
          LayoutLayer,
          //LinePickSensor,
          LineProperties,
          LineSet,
          LoadSensor,
          LocalFog,
          Material,
          Matrix3VertexAttribute,
          Matrix4VertexAttribute,
          MetadataBoolean,
          MetadataDouble,
          MetadataFloat,
          MetadataInteger,
          MetadataSet,
          MetadataString,
          //MotorJoint,
          MovieTexture,
          //MultiTexture,
          //MultiTextureCoordinate,
          //MultiTextureTransform,
          NavigationInfo,
          Normal,
          NormalInterpolator,
          //NurbsCurve,
          //NurbsCurve2D,
          //NurbsOrientationInterpolator,
          //NurbsPatchSurface,
          //NurbsPositionInterpolator,
          //NurbsSet,
          //NurbsSurfaceInterpolator,
          //NurbsSweptSurface,
          //NurbsSwungSurface,
          //NurbsTextureCoordinate,
          //NurbsTrimmedSurface,
          OrientationChaser,
          OrientationDamper,
          OrientationInterpolator,
          OrthoViewpoint,
          //PackagedShader,
          ParticleSystem,
          //PickableGroup,
          PixelTexture,
          //PixelTexture3D,
          PlaneSensor,
          PointEmitter,
          PointLight,
          //PointPickSensor,
          PointSet,
          Polyline2D,
          PolylineEmitter,
          Polypoint2D,
          PositionChaser,
          PositionChaser2D,
          PositionDamper,
          PositionDamper2D,
          PositionInterpolator,
          PositionInterpolator2D,
          //PrimitivePickSensor,
          //ProgramShader,
          ProximitySensor,
          QuadSet,
          //ReceiverPdu,
          Rectangle2D,
          //RigidBody,
          //RigidBodyCollection,
          ScalarChaser,
          ScalarDamper,
          ScalarInterpolator,
          ScreenFontStyle,
          ScreenGroup,
          Script,
          ShaderPart,
          //ShaderProgram,
          Shape,
          //SignalPdu,
          //SingleAxisHingeJoint,
          //SliderJoint,
          Sound,
          Sphere,
          SphereSensor,
          SplinePositionInterpolator,
          SplinePositionInterpolator2D,
          SplineScalarInterpolator,
          SpotLight,
          SquadOrientationInterpolator,
          StaticGroup,
          //StringSensor,
          SurfaceEmitter,
          Switch,
          TexCoordChaser2D,
          TexCoordDamper2D,
          Text,
          TextureBackground,
          TextureCoordinate,
          TextureCoordinate3D,
          TextureCoordinate4D,
          //TextureCoordinateGenerator,
          TextureProperties,
          TextureTransform,
          TextureTransform3D,
          TextureTransformMatrix3D,
          TimeSensor,
          TimeTrigger,
          //TouchGroup,
          TouchSensor,
          Transform,
          TransformSensor,
          //TransmitterPdu,
          TriangleFanSet,
          TriangleSet,
          TriangleSet2D,
          TriangleStripSet,
          TwoSidedMaterial,
          //UniversalJoint,
          Viewpoint,
          ViewpointGroup,
          Viewport,
          VisibilitySensor,
          VolumeEmitter,
          //VolumePickSensor,
          WindPhysicsModel,
          WorldInfo)
{
"use strict";

	var supportedNodes =
	{
		// 3.1
		MetadataBool:                 MetadataBoolean,
		// 3.3
		Anchor:                       Anchor,
		Appearance:                   Appearance,
		Arc2D:                        Arc2D,
		ArcClose2D:                   ArcClose2D,
		AudioClip:                    AudioClip,
		Background:                   Background,
		//BallJoint:                    BallJoint,
		Billboard:                    Billboard,
		BooleanFilter:                BooleanFilter,
		BooleanSequencer:             BooleanSequencer,
		BooleanToggle:                BooleanToggle,
		BooleanTrigger:               BooleanTrigger,
		BoundedPhysicsModel:          BoundedPhysicsModel,
		Box:                          Box,
		CADAssembly:                  CADAssembly,
		CADFace:                      CADFace,
		CADLayer:                     CADLayer,
		CADPart:                      CADPart,
		Circle2D:                     Circle2D,
		ClipPlane:                    ClipPlane,
		//CollidableOffset:             CollidableOffset,
		//CollidableShape:              CollidableShape,
		Collision:                    Collision,
		//CollisionCollection:          CollisionCollection,
		//CollisionSensor:              CollisionSensor,
		//CollisionSpace:               CollisionSpace,
		Color:                        Color,
		ColorChaser:                  ColorChaser,
		ColorDamper:                  ColorDamper,
		ColorInterpolator:            ColorInterpolator,
		ColorRGBA:                    ColorRGBA,
		ComposedCubeMapTexture:       ComposedCubeMapTexture,
		ComposedShader:               ComposedShader,
		//ComposedTexture3D:            ComposedTexture3D,
		Cone:                         Cone,
		ConeEmitter:                  ConeEmitter,
		//Contact:                      Contact,
		//Contour2D:                    Contour2D,
		//ContourPolyline2D:            ContourPolyline2D,
		Coordinate:                   Coordinate,
		CoordinateChaser:             CoordinateChaser,
		CoordinateDamper:             CoordinateDamper,
		CoordinateDouble:             CoordinateDouble,
		CoordinateInterpolator:       CoordinateInterpolator,
		CoordinateInterpolator2D:     CoordinateInterpolator2D,
		Cylinder:                     Cylinder,
		CylinderSensor:               CylinderSensor,
		//DISEntityManager:             DISEntityManager,
		//DISEntityTypeMapping:         DISEntityTypeMapping,
		DirectionalLight:             DirectionalLight,
		Disk2D:                       Disk2D,
		//DoubleAxisHingeJoint:         DoubleAxisHingeJoint,
		EaseInEaseOut:                EaseInEaseOut,
		ElevationGrid:                ElevationGrid,
		//EspduTransform:               EspduTransform,
		ExplosionEmitter:             ExplosionEmitter,
		Extrusion:                    Extrusion,
		//FillProperties:               FillProperties,
		FloatVertexAttribute:         FloatVertexAttribute,
		Fog:                          Fog,
		//FogCoordinate:                FogCoordinate,
		FontStyle:                    FontStyle,
		ForcePhysicsModel:            ForcePhysicsModel,
		GeneratedCubeMapTexture:      GeneratedCubeMapTexture,
		GeoCoordinate:                GeoCoordinate,
		GeoElevationGrid:             GeoElevationGrid,
		GeoLOD:                       GeoLOD,
		GeoLocation:                  GeoLocation,
		GeoMetadata:                  GeoMetadata,
		GeoOrigin:                    GeoOrigin,
		GeoPositionInterpolator:      GeoPositionInterpolator,
		GeoProximitySensor:           GeoProximitySensor,
		GeoTouchSensor:               GeoTouchSensor,
		GeoTransform:                 GeoTransform,
		GeoViewpoint:                 GeoViewpoint,
		Group:                        Group,
		//HAnimDisplacer:               HAnimDisplacer,
		//HAnimHumanoid:                HAnimHumanoid,
		//HAnimJoint:                   HAnimJoint,
		//HAnimSegment:                 HAnimSegment,
		//HAnimSite:                    HAnimSite,
		ImageCubeMapTexture:          ImageCubeMapTexture,
		ImageTexture:                 ImageTexture,
		//ImageTexture3D:               ImageTexture3D,
		IndexedFaceSet:               IndexedFaceSet,
		IndexedLineSet:               IndexedLineSet,
		IndexedQuadSet:               IndexedQuadSet,
		IndexedTriangleFanSet:        IndexedTriangleFanSet,
		IndexedTriangleSet:           IndexedTriangleSet,
		IndexedTriangleStripSet:      IndexedTriangleStripSet,
		Inline:                       Inline,
		IntegerSequencer:             IntegerSequencer,
		IntegerTrigger:               IntegerTrigger,
		KeySensor:                    KeySensor,
		LOD:                          LOD,
		Layer:                        Layer,
		LayerSet:                     LayerSet,
		Layout:                       Layout,
		LayoutGroup:                  LayoutGroup,
		LayoutLayer:                  LayoutLayer,
		//LinePickSensor:               LinePickSensor,
		LineProperties:               LineProperties,
		LineSet:                      LineSet,
		LoadSensor:                   LoadSensor,
		LocalFog:                     LocalFog,
		Material:                     Material,
		Matrix3VertexAttribute:       Matrix3VertexAttribute,
		Matrix4VertexAttribute:       Matrix4VertexAttribute,
		MetadataBoolean:              MetadataBoolean,
		MetadataDouble:               MetadataDouble,
		MetadataFloat:                MetadataFloat,
		MetadataInteger:              MetadataInteger,
		MetadataSet:                  MetadataSet,
		MetadataString:               MetadataString,
		//MotorJoint:                   MotorJoint,
		MovieTexture:                 MovieTexture,
		//MultiTexture:                 MultiTexture,
		//MultiTextureCoordinate:       MultiTextureCoordinate,
		//MultiTextureTransform:        MultiTextureTransform,
		NavigationInfo:               NavigationInfo,
		Normal:                       Normal,
		NormalInterpolator:           NormalInterpolator,
		//NurbsCurve:                   NurbsCurve,
		//NurbsCurve2D:                 NurbsCurve2D,
		//NurbsOrientationInterpolator: NurbsOrientationInterpolator,
		//NurbsPatchSurface:            NurbsPatchSurface,
		//NurbsPositionInterpolator:    NurbsPositionInterpolator,
		//NurbsSet:                     NurbsSet,
		//NurbsSurfaceInterpolator:     NurbsSurfaceInterpolator,
		//NurbsSweptSurface:            NurbsSweptSurface,
		//NurbsSwungSurface:            NurbsSwungSurface,
		//NurbsTextureCoordinate:       NurbsTextureCoordinate,
		//NurbsTrimmedSurface:          NurbsTrimmedSurface,
		OrientationChaser:            OrientationChaser,
		OrientationDamper:            OrientationDamper,
		OrientationInterpolator:      OrientationInterpolator,
		OrthoViewpoint:               OrthoViewpoint,
		//PackagedShader:               PackagedShader,
		ParticleSystem:               ParticleSystem,
		//PickableGroup:                PickableGroup,
		PixelTexture:                 PixelTexture,
		//PixelTexture3D:               PixelTexture3D,
		PlaneSensor:                  PlaneSensor,
		PointEmitter:                 PointEmitter,
		PointLight:                   PointLight,
		//PointPickSensor:              PointPickSensor,
		PointSet:                     PointSet,
		Polyline2D:                   Polyline2D,
		PolylineEmitter:              PolylineEmitter,
		Polypoint2D:                  Polypoint2D,
		PositionChaser:               PositionChaser,
		PositionChaser2D:             PositionChaser2D,
		PositionDamper:               PositionDamper,
		PositionDamper2D:             PositionDamper2D,
		PositionInterpolator:         PositionInterpolator,
		PositionInterpolator2D:       PositionInterpolator2D,
		//PrimitivePickSensor:          PrimitivePickSensor,
		//ProgramShader:                ProgramShader,
		ProximitySensor:              ProximitySensor,
		QuadSet:                      QuadSet,
		//ReceiverPdu:                  ReceiverPdu,
		Rectangle2D:                  Rectangle2D,
		//RigidBody:                    RigidBody,
		//RigidBodyCollection:          RigidBodyCollection,
		ScalarChaser:                 ScalarChaser,
		ScalarDamper:                 ScalarDamper,
		ScalarInterpolator:           ScalarInterpolator,
		ScreenFontStyle:              ScreenFontStyle,
		ScreenGroup:                  ScreenGroup,
		Script:                       Script,
		ShaderPart:                   ShaderPart,
		//ShaderProgram:                ShaderProgram,
		Shape:                        Shape,
		//SignalPdu:                    SignalPdu,
		//SingleAxisHingeJoint:         SingleAxisHingeJoint,
		//SliderJoint:                  SliderJoint,
		Sound:                        Sound,
		Sphere:                       Sphere,
		SphereSensor:                 SphereSensor,
		SplinePositionInterpolator:   SplinePositionInterpolator,
		SplinePositionInterpolator2D: SplinePositionInterpolator2D,
		SplineScalarInterpolator:     SplineScalarInterpolator,
		SpotLight:                    SpotLight,
		SquadOrientationInterpolator: SquadOrientationInterpolator,
		StaticGroup:                  StaticGroup,
		//StringSensor:                 StringSensor,
		SurfaceEmitter:               SurfaceEmitter,
		Switch:                       Switch,
		TexCoordChaser2D:             TexCoordChaser2D,
		TexCoordDamper2D:             TexCoordDamper2D,
		Text:                         Text,
		TextureBackground:            TextureBackground,
		TextureCoordinate:            TextureCoordinate,
		TextureCoordinate3D:          TextureCoordinate3D,
		TextureCoordinate4D:          TextureCoordinate4D,
		//TextureCoordinateGenerator:   TextureCoordinateGenerator,
		TextureProperties:            TextureProperties,
		TextureTransform:             TextureTransform,
		TextureTransform3D:           TextureTransform3D,
		TextureTransformMatrix3D:     TextureTransformMatrix3D,
		TimeSensor:                   TimeSensor,
		TimeTrigger:                  TimeTrigger,
		//TouchGroup:                   TouchGroup,
		TouchSensor:                  TouchSensor,
		Transform:                    Transform,
		TransformSensor:              TransformSensor,
		//TransmitterPdu:               TransmitterPdu,
		TriangleFanSet:               TriangleFanSet,
		TriangleSet:                  TriangleSet,
		TriangleSet2D:                TriangleSet2D,
		TriangleStripSet:             TriangleStripSet,
		TwoSidedMaterial:             TwoSidedMaterial,
		//UniversalJoint:               UniversalJoint,
		Viewpoint:                    Viewpoint,
		ViewpointGroup:               ViewpointGroup,
		Viewport:                     Viewport,
		VisibilitySensor:             VisibilitySensor,
		VolumeEmitter:                VolumeEmitter,
		//VolumePickSensor:             VolumePickSensor,
		WindPhysicsModel:             WindPhysicsModel,
		WorldInfo:                    WorldInfo,
	};

	function createInstance (executionContext) { return new this (executionContext); }

	for (var name in supportedNodes)
	{
		supportedNodes [name] .createInstance = createInstance .bind (supportedNodes [name]);
		supportedNodes [name.toUpperCase()] = supportedNodes [name]; 
		supportedNodes [name.toUpperCase()] .createInstance = createInstance .bind (supportedNodes [name]);
	}
	return supportedNodes;
});

